### ISSUE TITLE
Warnings for tel & sms links should not be generated

### ISSUE THREAD

**Issue by joelgaeddert** [dropseed/combine#41]
![CleanShot 2021-04-24 at 12 43 47](https://user-images.githubusercontent.com/6955859/115967889-bfb4ab80-a4fa-11eb-8ba0-bd5c338a9091.png)

These links are valid and should not throw a warning when running combine.

**Comment by davegaeddert** [comment]
Tel should already be ignored (I don't see an example in your screenshot). Added sms in [2.1.2](https://github.com/dropseed/combine/releases/tag/2.1.2).
